server:
  port: 8081

spring:
  application:
    name: log-collector
  main:
    web-application-type: reactive

collector:
  tcp:
    port: 9090
  udp:
    port: 9091
  
  blacklist:
    users:
      - root
      - admin
      - hacker
    ips:
      - 192.168.1.100
      - 10.0.0.50

logging:
  level:
    root: INFO
    com.logging: DEBUG