spring:
  application:
    name: client-service
  main:
    web-application-type: none

client:
  collector:
    host: localhost
    tcp-port: 9090
    udp-port: 9091
  
  log-interval:
    min: 1000
    max: 2000

logging:
  level:
    root: INFO
    com.logging: DEBUG